### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [buithuynhung/TuringMachine#1]
Пока программу собрать не удалось, поэтому смотрел бегло.

1. Собственно, не удалось собрать программу:
```
In file included from /home/gagarski/tmp/TuringMachine/main.c:1:
/home/gagarski/tmp/TuringMachine/declaration.h:35:1: error: unknown type name ‘errno_t’; did you mean ‘errno’?
 errno_t err;
 ^~~~~~~
 errno
/home/gagarski/tmp/TuringMachine/main.c: In function ‘loadTape’:
/home/gagarski/tmp/TuringMachine/main.c:8:5: error: unknown type name ‘errno_t’; did you mean ‘errno’?
     errno_t err = fopen_s(&in, "input.txt", "r");
     ^~~~~~~
     errno
/home/gagarski/tmp/TuringMachine/main.c:8:19: warning: implicit declaration of function ‘fopen_s’; did you mean ‘fopen’? [-Wimplicit-function-declaration]
     errno_t err = fopen_s(&in, "input.txt", "r");
                   ^~~~~~~
                   fopen
/home/gagarski/tmp/TuringMachine/main.c:14:9: warning: implicit declaration of function ‘fscanf_s’; did you mean ‘fscanf’? [-Wimplicit-function-declaration]
         fscanf_s(in, "%c ", &x, 1);
         ^~~~~~~~
         fscanf
make[2]: *** [CMakeFiles/TuringMachine.dir/build.make:63: CMakeFiles/TuringMachine.dir/main.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/TuringMachine.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```
Проблема в том, что вы используете нестандартные расширения, специфичные для вашего компилятора.
2. Согласно общим требованиям (см. документ со списком заданий) требуется сборка с помощью `make`, а не `cmake`. Сгенерированный `Makefile` не подойдёт, нужно написать свой вручную (он будет гораздо короче сгенерированного)
3. Мне не нравится формат файла `description.txt`,описание которого вы прислали с исправлениями к ТЗ. Конкретно то, что нужно явно задавать количество состояний и символов алфавита. Нельзя ли эти количества посчитать автоматически?
4. В исходноq формулировке задания (её, кстати, было бы неплохо включить в ТЗ) требуется следующее:

> Необходимо обеспечить возможность имитации работы машины до ее останова или в течение заданного числа шагов. Необходимо обеспечить возможность отладки машины (вывод промежуточных конфигураций, возобновление работы машины).

Намёков на это я в вашем коде при беглом просмотре не обнаружил.
5. Определитесь со стилем кодирования, в частности именования: 
https://github.com/buithuynhung/TuringMachine/blob/1c617aa247741ea0462fd2dae30054ddf9e39777/declaration.h#L36-L42
Здесь, например, в соседних строках соседствуют camelCase и snake_case
https://github.com/buithuynhung/TuringMachine/blob/1c617aa247741ea0462fd2dae30054ddf9e39777/declaration.h#L7-L20
Здесь typedef сделан в разном стиле.
6. Всю выделяемую `malloc` память нужно освобождать после того, как она не используется. Ни одного вызова `free` я не нашёл.
7. `#pragma once` тоже нестандартное расширение, хотя и поддерживается всеми компиляторами
8. https://github.com/buithuynhung/TuringMachine/blob/1c617aa247741ea0462fd2dae30054ddf9e39777/declaration.h#L33-L34
Глобальных переменных в коде быть не должно. **Тем более** они не должны быть определены ("defined"  в терминах стандарта) в заголовочном файле.

**Comment by buithuynhung** [comment]
Я уже испрвила ошибки. Проверьте, пожалуйста!

**Comment by buithuynhung** [comment]
Вы можете подсказать, пожалуйста, как обеспечить бесконечную ленту?

**Comment by buithuynhung** [comment]
Я исправила все замечания кроме пункта 5. Проверьте пожалуйста!

**Comment by gagarski** [comment]
Готов обсуждать завтра. Было бы здорово, если бы вы добавили какой-нибудь содержательный пример машины для каких-либо вычислений (либо описание из вашего первого задания, либо что-нибудь ещё более простое).
